name: Deploy BDShips

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "✅ Setting Git safe directory..."
            git config --global --add safe.directory /var/www/bdships

            echo "✅ Fixing permissions..."
            sudo chown -R deploy:deploy /var/www/bdships
            sudo chmod -R 755 /var/www/bdships

            echo "✅ Pull latest code..."
            cd /var/www/bdships
            git reset --hard
            git pull origin main

            echo "✅ Install dependencies..."
            npm install

            echo "✅ Build project..." 
            npm run build

            echo "✅ Reload PM2 process using ecosystem.config.js..."
            pm2 describe bdships || pm2 start ecosystem.config.js
            pm2 reload ecosystem.config.js --update-env